print(type("Hello"))
print(type(123))
print(type(123.3))
print(type(True))
name_of_the_user = input("Enter your name:")
len_of_name= len(name_of_the_user)
print(type("Number of letters in your name: "))
print(type(len_of_name))
print("Number of letters in your name: " + str(len_of_name))